CREATE TABLE "mytable" (
  "-- ## 2. Understanding lead conversions ## --" text
);

INSERT INTO "mytable" ("-- ## 2. Understanding lead conversions ## --")
VALUES
('-- 1. Identify total no. of transactions with campaign coupon vs without campaign coupon.'),
('SELECT ''Purchase_without_coupon'' as ''Coupon_Status'''),
('COUNT(Trans_Id) ''No_of_Trans'''),
('FROM CustomerTransactionData'),
('WHERE coupon_id IS NULL'),
('UNION ALL'),
('SELECT ''Purchase_with_coupon'' as ''Coupon_Status'''),
('COUNT(Trans_Id) ''No_of_Trans'''),
('FROM CustomerTransactionData'),
('WHERE coupon_id IS NOT NULL;'),
('-- 2. identify the name of potential leads who have made a purchase but have not yet used a campaign coupon'),
('SELECT C.Customer_Id'),
('C.Name'),
('COUNT(Trans_Id) AS NumberOfPurchase'),
('FROM Customer C'),
('INNER JOIN CustomerTransactionData CT'),
('ON C.Customer_Id = CT.Cust_Id'),
('WHERE coupon_id IS NULL'),
('GROUP BY C.Customer_Id'),
('-- ## 3. Understanding customer engagement ## --'),
('-- 1. Which customers have used the most coupons and what is the total price'),
('SELECT TOP(1)'),
('C.Customer_Id'),
('C.Name'),
('COUNT(coupon_id) AS ''No_of_Coupons'''),
('SUM(PurchasingAmt) AS ''Total_Price'''),
('FROM Customer C'),
('INNER JOIN CustomerTransactionData CT'),
('ON C.Customer_Id = CT.Cust_Id'),
('WHERE coupon_id IS NOT NULL'),
('GROUP BY C.Customer_Id'),
('ORDER BY 3 DESC'),
('-- 2. Name of customer in Which city have the highest number of transactions and what is the total'),
('SELECT TOP(1) Cust_Id'),
('C.City_Id'),
('SUM(PurchasingAmt) ''Purchase_Amt'''),
('FROM CustomerTransactionData CT'),
('INNER JOIN Customer C'),
('ON C.Customer_Id = CT.Cust_Id'),
('INNER JOIN City CY'),
('ON CY.City_ID = C.City_ID'),
('WHERE CY.City_Id = (SELECT City_ID FROM'),
('(SELECT TOP(1) City_Name'),
('COUNT(Trans_Id) AS ''Total_Trans'''),
('ROUND(SUM(PurchasingAmt)'),
('FROM CustomerTransactionData CT'),
('INNER JOIN Customer CS'),
('ON CT.Cust_Id = CS.Customer_Id'),
('INNER JOIN City CY'),
('ON CY.City_Id = CS.City_Id'),
('GROUP BY City_Name'),
('ORDER BY 3 DESC'),
('GROUP BY Cust_Id'),
('ORDER BY 5 DESC ;'),
('-- ## 4. Automating the Task ## --'),
('-- 1. Create view for top 10 Customers by Purchasing Amount'),
('GO'),
('CREATE VIEW vw_Top10CustomerPurchase AS'),
('(SELECT TOP(10) CT.Cust_Id'),
('SUM(PurchasingAmt) AS ''Total_Sales'''),
('FROM CustomerTransactionData CT'),
('INNER JOIN Customer C'),
('ON C.Customer_Id = CT.Cust_Id'),
('GROUP BY CT.Cust_Id'),
('ORDER BY 3 DESC) ;'),
('GO'),
('select * from vw_Top10CustomerPurchase ;'),
('-- 2. Top 5 Customers (from Household and Industrial Sector) Based on Purchase Amount'),
('GO'),
('CREATE VIEW vw_Top5CustBySector AS'),
('(SELECT TOP(5) C.Name'),
('FROM CustomerTransactionData CT'),
('INNER JOIN Customer C'),
('ON C.Customer_Id = CT.Cust_Id'),
('WHERE OrderType IN (''Household'''),
('GROUP by C.Name'),
('ORDER BY 3 DESC) ;'),
('GO'),
('SELECT * from vw_Top5CustBySector;');
