CREATE TABLE "mytable" (
  "-- ## SECTION 1: OVERVIEW OF THE DATA ## --" text
);

INSERT INTO "mytable" ("-- ## SECTION 1: OVERVIEW OF THE DATA ## --")
VALUES
('-----------------------------------------------------------------------------------'),
('-- Q1. Check the cardinality of following columns (Counts)'),
('-- 1. Different type of paints provided by the company.'),
('SELECT COUNT(DISTINCT(Item_Category)) Category_count FROM Item;'),
('-- 2. Different Coupon Types that are offered'),
('SELECT COUNT(DISTINCT couponType) Coupon_Count FROM CouponMapping ;'),
('-- 3. States where the company is currently delivering its products and services.'),
('SELECT COUNT(DISTINCT State) City_Count FROM City;'),
('-- 4. Different Order Types.'),
('SELECT COUNT(DISTINCT OrderType) OrderType_Count FROM CustomerTransactionData;'),
('-----------------------------------------------------------------------------------'),
('-- Q2. Identify total number of sales (transactions) happened by'),
('-- 1. Yearly basis'),
('SELECT YEAR(PurchaseDate) Year'),
('COUNT(Trans_Id) AS Total_Trans'),
('FROM CustomerTransactionData'),
('GROUP BY YEAR(PurchaseDate);'),
('-- 2. Quarterly basis'),
('SELECT DATEPART(QUARTER'),
('COUNT(Trans_Id) AS Total_Trans'),
('FROM CustomerTransactionData'),
('GROUP BY DATEPART(QUARTER'),
('-- 3. Yearly and Monthly basis'),
('SELECT DATEPART(YEAR'),
('DATEPART(MONTH'),
('COUNT(Trans_Id) AS Total_Trans'),
('FROM CustomerTransactionData'),
('GROUP BY DATEPART(YEAR'),
('-----------------------------------------------------------------------------------'),
('-- Q3. Identify the total purchase order by'),
('-- 1. Product category'),
('SELECT I.Item_Category'),
('SUM(PurchasingAmt) AS Total_Sales'),
('FROM CustomerTransactionData AS C'),
('JOIN'),
('Item AS I'),
('ON C.item_id = I.item_id'),
('GROUP BY I.Item_Category;'),
('-- 2. Yearly and Quarterly basis'),
('SELECT DATEPART(YEAR'),
('DATEPART(QUARTER'),
('round(SUM(PurchasingAmt)'),
('FROM CustomerTransactionData'),
('GROUP BY DATEPART(YEAR'),
('-- 3. Order Type'),
('SELECT OrderType'),
('round(SUM(PurchasingAmt)'),
('FROM CustomerTransactionData'),
('GROUP BY OrderType;'),
('-- 4. City Tier'),
('SELECT CityTier'),
('round(SUM(PurchasingAmt)'),
('FROM CustomerTransactionData AS CT'),
('JOIN Customer AS C'),
('ON C.Customer_Id = CT.Cust_Id'),
('JOIN City'),
('ON City.City_Id = C.City_Id'),
('GROUP BY CityTier;');
